# Generated by Django 2.0.5 on 2018-06-07 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='한글 200자', max_length=600, verbose_name='질문')),
                ('answer', models.CharField(help_text='한글 200자', max_length=600, verbose_name='응답')),
                ('verify', models.IntegerField(choices=[(0, '검토전'), (1, '검토완료'), (2, '삭제필요')], help_text='0:검토전, 1:검토완료, 2:삭제필요', verbose_name='검토')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Category')),
            ],
        ),
    ]
